In [1]:
# OPTIONAL: Load the "autoreload" extension so that code can change
%load_ext autoreload

# OPTIONAL: always reload modules so that as you change code in src, it gets loaded
%autoreload 2

In [2]:
import torch

/home/fptu/.local/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [9]:
from model.CmmlLayer import CmmlModel
import pandas as pd

In [20]:
parser = pd.Series()
parser = pd.concat([parser, pd.Series({'Textfeaturepara': "3000, 256, 128"})])
parser = pd.concat([parser, pd.Series({'Imgpredictpara': "128, 1"})])
parser = pd.concat([parser, pd.Series({'Textpredictpara': "128, 1"})])
parser = pd.concat([parser, pd.Series({'Predictpara': "128, 1"})])
parser = pd.concat([parser, pd.Series({'Attentionparameter': "128, 64, 32, 1"})])
parser = pd.concat([parser, pd.Series({'add_block_linear_bert_embed': False})])
parser = pd.concat([parser, pd.Series({'output_backbone_dim': 128})])
parser = pd.concat([parser, pd.Series({'use_vcreg_loss': False})])

args = parser
args

/tmp/ipykernel_2177001/735052684.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  parser = pd.Series()


Textfeaturepara                3000, 256, 128
Imgpredictpara                         128, 1
Textpredictpara                        128, 1
Predictpara                            128, 1
Attentionparameter             128, 64, 32, 1
add_block_linear_bert_embed             False
output_backbone_dim                       128
use_vcreg_loss                          False
dtype: object

In [21]:
model = CmmlModel(args)


In [22]:
# Specify a path
PATH = "../tmp/model_fail.pt"

model.load_state_dict(torch.load(PATH))
# model.eval()

<All keys matched successfully>

In [24]:
for name, param in model.named_parameters():
    if torch.isnan(param).sum()>0:
        print(name, param)

Imgpredictmodel.mlp.0.weight Parameter containing:
tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan]], requires_grad=True)
Imgpredictmodel.mlp.0.bias Parameter containing:
tensor([nan], requires_grad=True)
Imgmodel.feature.0.weight Parameter containing:
tensor([[[[        nan,         nan,         nan,  ...,         nan,
                   nan,         n

In [25]:
print(model.Imgmodel)

ImgNet(
  (feature): Sequential(
    (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (4): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
